---
- hosts: dev
  tasks:
    - name: creating a directory
      file:
        path: /tmp/gamefolder
        state: directory

    - name: copy war file 
      copy: 
        src: "{{ workspace }}/gameoflife-0.0.1.war"
        dest: "/tmp/gamefolder/gameoflife-0.0.1.war"

    - name: executing war
      shell: java -jar /tmp/gamefolder/gameoflife-0.0.1.war
      become: true
